- name: Install required packages
  apt:
    name: "{{ example_packages }}"
    state: present
    update_cache: yes

- name: Configure example tool
  template:
    src: example_config.j2
    dest: /etc/example/example.conf
